### ISSUE TITLE
Comentario.

### ISSUE THREAD

**Issue by Eliezer3104** [uETITC/ProgrammingII-2024-2#1]
Está bien organizada la estructura de directorios, aunque los nombres de las carpetas no son claros, también hace falta el uso de imágenes que ayuden claramente el propósito del proyecto, me gusta que tenga enlaces a documentación adicional o recursos relacionados, se utilizan correctamente ramas para desarrollo, pruebas y producción, me gusta que se usa e Incluye instrucciones de instalación, uso y desarrollo, y los códigos tienen suficientes comentarios para entenderlo sin dificultad.

**Comment by saguileran** [comment]
Este es el repositorio del curso, no del proyecto de los otros compañeros.
